# Generated by Django 3.2.4 on 2022-09-22 20:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=250)),
                ('cover_letter', models.TextField(null=True)),
                ('address', models.CharField(max_length=500)),
                ('apply_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_selected', models.BooleanField(default=False)),
            ],
        ),
    ]
