# Generated by Django 3.2.4 on 2022-09-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_applicant_cover_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='resume',
            field=models.FileField(null=True, upload_to='docs'),
        ),
    ]
